[package]
name = "chunkIQ"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
crossbeam = { version = "0.8.4" }
digest = "0.10.7"
memmap2 = "0.9.5"
sha1 = "0.10.6"
