name: Rust Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        BUILD_TARGET: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}

      # - name: Check project
      #   run: cargo check
